import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// importing fontawesome
// preventing css property to be automatically added
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Istamosh Portfolio",
  description: "Generated by create next app",
};

// this is the base layout section for Next app
// can embed the theme here
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="night">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
